server:
  port: 8081

spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true
  http:
    multipart:
      enabled: true
      location: /
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false

mybatis:
  type-aliases-package: com.xianqu.bean,com.xianqu.vo
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect:mysql
  reasonable:true
  supportMethodsArguments:true

aliyun:
  oss:
    endpoint: oss-cn-beijing-internal.aliyuncs.com
    accessKeyId: LTAI5SERkKutpEwm
    accessKeySecret: NGIhDjrGUvrHoMak0VJQJYndPCT5Rq
    bucketName: easy-time
    picLocation: product/
