server:
  port: 8081

spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true

mybatis:
  type-aliases-package: com.xianqu.bean,com.xianqu.vo
  mapper-locations: classpath:mapper/*.xml

