spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homepage?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: wenchen123